# model_config.yaml
model:
  vocab_size: 50304
  context_length: 1024
  d_model: 768
  n_heads: 12
  n_layers: 12
  bias: true

training:
  total_batch_size: 524288
  micro_batch_size: 16
  max_steps: 10681          # 10681 × 524288 ≈ 5.6B tokens
  warmup_steps: 400        # 3.75% of max_steps
  max_lr: 6.0e-4
  min_lr: 6.0e-5
  val_interval: 250
  hella_interval: 250
  ckpt_interval: 2500

paths:
  tokenizer: null
  shards_dir: "artifacts/shards"
  log_dir: "log"

logging:
  wandb_project: "llm-playground"
  wandb_run_name: "gpt-110M-5B-fineweb-edu"
  wandb_enabled: true